# This is the OpenAPI specification for your service. It is used to generate the client code.
# To generate the server code, use the Gradle task `openApiGenerate`. The 
# generated code will be placed in `build/generate-resources/main`.
#
# We will evaluate you based on how well you design your API.
# 1. How well it follows REST principles.
# 2. How easy it is to understand and use.
#
# References
# 1. https://swagger.io/specification/
openapi: "3.0.0"
info:
  version: 1.0.0
  title: User Service
  license:
    name: MIT
servers:
  - url: http://localhost
paths:
  /hello:
    get:
      summary: This is just a test endpoint to get you started.
      responses:
        '200':
          description: Test return
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/HelloResponse"
  /estate:
    post:
      summary: Create and store a new estate
      description: Creates and stores a new palm oil plantation estate in the database.
        Receives two integers, width and length, representing the number of 10x10m² plots.
        Both values must be between 1 and 50000.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateEstateRequest"
      responses:
        '200':
          description: Estate successfully created; returns a UUIDv4 string representing the estate.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateEstateResponse"
        '400':
          description: Invalid input, such as values out of range or incorrect format.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    HelloResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: Hello, World!
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "Invalid request"
    CreateEstateRequest:
      type: object
      properties:
        width:
          type: integer
          minimum: 1
          maximum: 50000
          example: 5
        length:
          type: integer
          minimum: 1
          maximum: 50000
          example: 10
      required:
        - length
        - width
    CreateEstateResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: "UUID of the newly created estate"
          example: "aaaaaa-bbbbbb-cccccc-ddddd"